This jupyter notebook is part of the supplementary material for the book "Materials Data Science" (Stefan Sandfeld, Springer, 2024, DOI 10.1007/978-3-031-46565-9). For further details please refer to the accompanying webpage https://mds-book.org.

## 3.2 Sets, Tuples, Vectors, and Arrays

### 3.2.1 Sets

<div class="alert alert-block alert-info">
<b>Definition 3.2 (Set):</b> 
A mathematical set is an unstructured collection of different elements without repetitions. Elements can be, e.g., numbers, variables,
symbols, or also other sets. We indicate a set by curly braces, and elements are separated by commas. For example, the set of the numbers 7, 1, 4, 2, and
8 is written as $\{7, 1, 4, 2, 8\}$.
</div>

In Python two sets of numbers can be compared by

In [18]:
set([3, 4, 5]) == set([4, 3, 5, 3])

True

Python already has the most common set operations built in:

In [19]:
# Create two sets:
A = {'a', 'bb', 'c'}
B = {'A', 'bb', 'd', 42}

In [20]:
# Union of the two sets:
set.union(A, B)

{42, 'A', 'a', 'bb', 'c', 'd'}

In [21]:
# Alternative for writing the union:
A | B

{42, 'A', 'a', 'bb', 'c', 'd'}

In [22]:
# Intersection of A and B
set.intersection(A, B)

{'bb'}

In [23]:
# Alternative for writing the intersection:
A & B

{'bb'}

In [24]:
# Difference A \ B
A - B  # or set.difference(A, B)

{'a', 'c'}

In [25]:
# Difference B \ A
B - A  # or set.difference(B, A)

{42, 'A', 'd'}

## 3.2.2 Tuple
<div class="alert alert-block alert-info">
<b>Definition 3.3 (Tuple):</b> 
A tuple is a collection of elements such as numbers,
variables, or symbols that occur in an ordered manner, where repetition
matters. This is indicated by parenthesis, and elements are separated by
commas. For example, the tuple of the letters m, d, and s is written as
$(m, d, s)$. Sometimes also square brackets are used, e.g., $[4, 5, 5, 1]$.
</div>

As opposed to the set, Python’s tuple and list do consider repeated elements (note that only the elements of the list can be altered, not that of a tuple!),
as shown in this example:

In [26]:
list([1, 3, 5]) == list([1, 3, 3, 5, 5])

False

A number of operations on Python lists and tuple exists; please refer to the Python documentation for more details.

## 3.2.4 Matrices, Row and Column Vectors

E.g., use Numpy to create a matrix with 3 rows and 4 columns containing zeros:

In [27]:
import numpy
A = numpy.zeros((3, 4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
# set the element in the second row and third column to the value 1.2:
A[1, 2] = 1.2
A

array([[0. , 0. , 0. , 0. ],
       [0. , 0. , 1.2, 0. ],
       [0. , 0. , 0. , 0. ]])

In [29]:
# set all elements of the 3rd row:
A[2, :] = 3   # alternative: A[2, ...] or A[2]
A

array([[0. , 0. , 0. , 0. ],
       [0. , 0. , 1.2, 0. ],
       [3. , 3. , 3. , 3. ]])