This jupyter notebook is part of the supplementary material for the book "Materials Data Science" (Stefan Sandfeld, Springer, 2024, DOI 10.1007/978-3-031-46565-9). For further details please refer to the accompanying webpage https://mds-book.org.

## 3.3 Representation of Data in Statistics and Machine Learning

### Example 3.3 and 3.4: Representation of a Measurement Dataset
Create feature vectors and the target vector as 1D arrays:

In [1]:
import numpy as np
X1 = np.array([0, 10, 20, 30, 40, 50, 60], dtype=float)
X2 = np.array([1010, 1010, 1010, 1010, 1013, 1013, 1013], dtype=float)
Y = np.array([180, 170, 160, 150, 140, 130, 120], dtype=float)
X1

array([ 0., 10., 20., 30., 40., 50., 60.])

Convert them to column vectors, i.e., two-dimensional arrays with only
one column:

In [2]:
X1 = X1.reshape(-1, 1)
X2 = X2.reshape(-1, 1)
Y = Y.reshape(-1, 1)
X1

array([[ 0.],
       [10.],
       [20.],
       [30.],
       [40.],
       [50.],
       [60.]])

Create the feature matrix X and the data matrix D

In [3]:
X = np.hstack((X1, X2))
D = np.hstack((X, Y))
D

array([[   0., 1010.,  180.],
       [  10., 1010.,  170.],
       [  20., 1010.,  160.],
       [  30., 1010.,  150.],
       [  40., 1013.,  140.],
       [  50., 1013.,  130.],
       [  60., 1013.,  120.]])

Use these variables for answering the questions (iii) - (v) from Example 3.3): 

- (iii) What is the data record number 2? 
- (iv) What is the first feature? 
- (v) What is the input record number 3?

Note that Python is 0-based, i.e., the first element has the index 0!

In [4]:
print("(iii) P(2) =", D[1])
print("(iv)  X1   =", X[:, 0])
print("(v)   x_3  =", X[2])

(iii) P(2) = [  10. 1010.  170.]
(iv)  X1   = [ 0. 10. 20. 30. 40. 50. 60.]
(v)   x_3  = [  20. 1010.]
