<div class="alert alert-block alert-success">
This jupyter notebook is part of the supplementary material for the book "Materials Data Science" (Stefan Sandfeld, Springer, 2024, DOI 10.1007/978-3-031-46565-9). For further details please refer to the accompanying webpage at <a href="https://mds-book.org">https://mds-book.org</a>.
</div>

In [1]:
import matplotlib.pyplot as plt
import numpy as np

## 13.2 Generalized Formulations and Vectorization for Multiple Linear Regression
#### Example 13.1: Vectorized Linear Regression in Python

In [2]:
# feature matrix with 1 feature
X = np.array([1.1, 2.2, 3.0, 3.9]).reshape(-1, 1)

# target vector (1 column)
Y = np.array([1.3, 2.4, 2.9, 3.6]).reshape(-1, 1)

# (initial) weights in 1 column
weights = np.array([-0.5, 0.2]).reshape(-1, 1)

# number of data records
n_records = X.shape[0]

In [3]:
X

array([[1.1],
       [2.2],
       [3. ],
       [3.9]])

Create the "extended feature matrix" by prepending a columns of 1s:

In [4]:
# stack arrays horizontally
IX = np.hstack((np.ones_like(X), X))
IX

array([[1. , 1.1],
       [1. , 2.2],
       [1. , 3. ],
       [1. , 3.9]])

Next, the closed form solution for the weights, $\boldsymbol{w}^∗$ , for which the loss function reaches
a minimum is implemented. There, the numpy function `inv` from the `linalg` module was used for inverting
$\mathbb{X}^\text{T} \mathbb{X}$.

In [5]:
exact_weights = np.linalg.inv(IX.T @ IX) @ IX.T @ Y

Y_pred = IX @ exact_weights

Y_pred

array([[1.37635294],
       [2.26670588],
       [2.91423529],
       [3.64270588]])

Comparing this result to the elements of `Y` shows that the two results are quite close:

In [6]:
Y

array([[1.3],
       [2.4],
       [2.9],
       [3.6]])